I removed #egg parts in cafe_requirements.txt.
The git checkouts seem to have metadata in them to provide the package
name.

By all appearances, I shouldn't need to do this:
https://pip.readthedocs.io/en/1.1/requirements.html

However, using pip 18.1, with the #egg syntax, it works on my local
Mac, and fails on the dev VM with the same pip version. It appears to
work fine without it.

I ran pip -v, and (despite having the same version of pip in both
places), the output looks different.

From my Mac, where it works, you see:

```
  Running command git show-ref b971070b28d07c0b19f8809e18950f2d6cf0e466
  Running command git rev-parse HEAD
  c3f341eb29f701163435e3afbf4794aa94feff2d
  Running command git checkout -q b971070b28d07c0b19f8809e18950f2d6cf0e466
  Added cafe from git+https://github.com/stackforge/opencafe.git@b971070b28d07c0b19f8809e18950f2d6cf0e466#egg=cafe (from -r cafe_requirements.txt (line 1)) to build tracker
```

From the dev VM, you see:

```
  Running command git clone -q https://github.com/stackforge/opencafe.git /tmp/pip-install-NCHPoI/cafe
  Running command git show-ref b971070b28d07c0b19f8809e18950f2d6cf0e466#egg=cafe
  Running command git rev-parse HEAD
  c3f341eb29f701163435e3afbf4794aa94feff2d
  Running command git checkout -q b971070b28d07c0b19f8809e18950f2d6cf0e466#egg=cafe
error: pathspec 'b971070b28d07c0b19f8809e18950f2d6cf0e466#egg=cafe' did not match any file(s) known to git.
```

This makes no sense. However, `pip list` on the dev VM reveals that the
packages get installed with the right name anyway, and it works this way.